### ISSUE TITLE
Wrong version of Python

### ISSUE THREAD

**Issue by andrew-m-higgs** [algorand-coding-challenges/python-challenge-1#43]
Hi there

I hope someone is able to help. I really would like to complete this challenge.

When I run ```algokit bootstrap all```, poetry complains about the incorrect version of Python. Ubuntu 22.04.1 uses 3.10.12 as its standard. I installed Python 3.12 and set it in ```update-alternatives``` to point to python. So if you run ```python --version``` you get 3.12.2 and if you run ```python3 --version``` you get 3.10.12. It still failed.

So I installed 3.12.2 using ```pyenv```. Still fails. I am not sure how to get this project to see the right version of Python.

Any assistance would be greatly appreciated. Thanks in advance.

**Comment by andrew-m-higgs** [comment]
I have also tried ```poetry env use 3.12.2```. This complained about missing a pyproject.toml file. I created one using ```poetry init```. Still not working.

**Comment by andrew-m-higgs** [comment]
In case anyone else is struggling with this. Try ```pyenv install 3.12.2``` then, in the project directory run ```pyenv local 3.12.2``` and ```algokit bootstrap all``` should work.

**Comment by iskysun96** [comment]
glad you were able to figure it out Andrew. Yeah Python version control is a nightmare sometimes. 😅 I also use pyenv for Python version control.
